name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Make a change
        run: |
          date >> daily-commit.log

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "22f3000522@ds.study.iitm.ac.in"
          git add daily-commit.log
          git commit -m "Daily commit $(date)"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/22f3002334/daily-commit.git

